# Generated by Django 4.0.4 on 2022-05-26 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del bloque')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
            },
        ),
        migrations.CreateModel(
            name='BookingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del espacio que se puede reservar')),
            ],
            options={
                'verbose_name': 'Espacio de reserva',
                'verbose_name_plural': 'Espacios de reserva',
            },
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de la zona de parqueo')),
            ],
            options={
                'verbose_name': 'Zona de parqueo',
                'verbose_name_plural': 'Zonas de parqueo',
            },
        ),
        migrations.CreateModel(
            name='PenaltyFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del tipo de multa')),
            ],
            options={
                'verbose_name': 'Tipo de multa',
                'verbose_name_plural': 'Tipos de multas',
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa')], max_length=30, verbose_name='Tipo de residencia')),
                ('number', models.PositiveIntegerField(verbose_name='Número de residencia')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('busy', models.BooleanField(default=True, verbose_name='¿Está ocupada?')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.block', verbose_name='Bloque')),
            ],
            options={
                'verbose_name': 'Residencia',
                'verbose_name_plural': 'Residencias',
            },
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del color del vehiculo')),
            ],
            options={
                'verbose_name': 'Color de vehiculo',
                'verbose_name_plural': 'Colores de vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del tipo de vehiculo')),
            ],
            options={
                'verbose_name': 'Tipo de vehiculo',
                'verbose_name_plural': 'Tipos de vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=250, null=True, verbose_name='Placa del vehiculo')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
                ('vehicle_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.vehiclecolor', verbose_name='Color del vehiculo')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.vehicletype', verbose_name='Tipo de vehiculo')),
            ],
            options={
                'verbose_name': 'Tipo de vehiculo',
                'verbose_name_plural': 'Tipos de vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=900, null=True, verbose_name='Descripción de la multa')),
                ('details', models.CharField(blank=True, max_length=900, null=True, verbose_name='Descripción de la multa')),
                ('reception_date', models.DateTimeField(verbose_name='Fecha de recepción')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_type', models.CharField(choices=[('tenant', 'Arrendatario'), ('habitant', 'Habitante'), ('owner', 'Propietario')], max_length=30, verbose_name='Tipo de residente')),
                ('first_name', models.CharField(max_length=250, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp')),
                ('active', models.BooleanField(verbose_name='¿Está activa?')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
            },
        ),
        migrations.CreateModel(
            name='PenaltyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900, verbose_name='Descripción de la multa')),
                ('penalty_fee_date', models.DateTimeField(verbose_name='Fecha de la multa')),
                ('amount_to_paid', models.PositiveBigIntegerField(default=0, verbose_name='Monto a pagar')),
                ('active', models.BooleanField(verbose_name='¿Está activa?')),
                ('penalty_fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.penaltyfeetype', verbose_name='Tipo de multa')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250, verbose_name='Número del espacio de parqueo')),
                ('parking_space_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.vehicle', verbose_name='Tipo de espacio/vehiculo')),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.parkingzone', verbose_name='Zona del espacio de parqueo')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Espacio de parqueo',
                'verbose_name_plural': 'Espacios de parqueo',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio de la reserva')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de fin de la reserva')),
                ('booking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.bookingspace', verbose_name='Espacio que reserva')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
