# Generated by Django 4.0.4 on 2022-05-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0003_delete_parkingspace_delete_parkingzone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PenaltyFee',
        ),
        migrations.DeleteModel(
            name='PenaltyFeeType',
        ),
    ]
