# Generated by Django 4.0.4 on 2022-05-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0004_delete_penaltyfee_delete_penaltyfeetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingSpace',
        ),
    ]
