# Generated by Django 4.0.4 on 2022-05-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0005_delete_booking_delete_bookingspace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
