# Generated by Django 4.0.4 on 2022-05-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0009_alter_resident_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre del bloque'),
        ),
        migrations.AlterUniqueTogether(
            name='residence',
            unique_together={('block', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='resident',
            unique_together={('residence', 'resident_type', 'first_name', 'last_name')},
        ),
    ]
