# Generated by Django 4.0.4 on 2022-05-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residential', '0007_remove_vehicle_residence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del color del vehiculo')),
            ],
            options={
                'verbose_name': 'Color de vehiculo',
                'verbose_name_plural': 'Colores de vehiculos',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del tipo de vehiculo')),
            ],
            options={
                'verbose_name': 'Tipo de vehiculo',
                'verbose_name_plural': 'Tipos de vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(blank=True, max_length=250, null=True, verbose_name='Placa del vehiculo')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
                ('vehicle_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclecolor', verbose_name='Color del vehiculo')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicletype', verbose_name='Tipo de vehiculo')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
    ]
