# Generated by Django 4.0.4 on 2022-05-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=250, unique=True, verbose_name='Placa del vehiculo'),
        ),
    ]
