# Generated by Django 4.0.4 on 2022-05-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residential', '0003_delete_parkingspace_delete_parkingzone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de la zona de parqueo')),
            ],
            options={
                'verbose_name': 'Zona de parqueo',
                'verbose_name_plural': 'Zonas de parqueo',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250, verbose_name='Número del espacio de parqueo')),
                ('parking_space_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.vehicle', verbose_name='Tipo de espacio/vehiculo')),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_lot.parkingzone', verbose_name='Zona del espacio de parqueo')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Espacio de parqueo',
                'verbose_name_plural': 'Espacios de parqueo',
            },
        ),
    ]
