# Generated by Django 4.0.4 on 2022-05-30 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residential', '0004_delete_penaltyfee_delete_penaltyfeetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyFeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del tipo de multa')),
            ],
            options={
                'verbose_name': 'Tipo de multa',
                'verbose_name_plural': 'Tipos de multas',
            },
        ),
        migrations.CreateModel(
            name='PenaltyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=900, verbose_name='Descripción de la multa')),
                ('penalty_fee_date', models.DateTimeField(verbose_name='Fecha de la multa')),
                ('amount_to_paid', models.PositiveBigIntegerField(default=0, verbose_name='Monto a pagar')),
                ('active', models.BooleanField(verbose_name='¿Está activa?')),
                ('penalty_fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fines.penaltyfeetype', verbose_name='Tipo de multa')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residential.residence', verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
            },
        ),
    ]
