# Generated by Django 4.0.4 on 2022-05-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Descripción del envío'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='details',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='Detalles del envío'),
        ),
    ]
